## 파일 입출력

In [1]:
import os
os.getcwd()

'C:\\Users\\bean\\Desktop\\mtc_28\\python\\ML'

In [2]:
import pandas as pd

sample_df = pd.DataFrame({"col1" : [1, 2], "col2" : [3, 4]})
sample_df

sample_df.to_csv("./output/sample/test.csv", index=False)

print("csv 파일을 저장했습니다.")

csv 파일을 저장했습니다.


## 파일 불러오기
- sample 폴더안에 test.csv 불러오기

In [3]:
df = pd.read_csv(filepath_or_buffer="./output/sample/test.csv")

df

col1  col2
0     1     3
1     2     4

In [4]:
df_boston = pd.read_csv(filepath_or_buffer="./data/boston.csv")

df_boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

## 열 및 행 선택
- CRIM, ZN, INDUS 열을 선택함

In [5]:
cols = ["CRIM", "ZN", "INDUS"]
result = df_boston[cols]

result.head()

CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07
2  0.02729   0.0   7.07
3  0.03237   0.0   2.18
4  0.06905   0.0   2.18

- ZN == 18.0 에 해당하는 행만 추출

In [6]:
result = df_boston[df_boston["ZN"] == 18.0]
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  target  
0  396.9   4.98    24.0

- AGE가 50 이상인 데이터만 추출

In [7]:
row = df_boston[df_boston['AGE'] >= 50].reset_index(drop = True)
row

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
4    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
354  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
355  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
356  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
357  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
358  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  396.90   5.33    36.2  
4       18.7  394.12   5.21    28.7  
..       ...     ...    ...     ...  
354     21.0  391.99   9.67    22.4  
355     21.0  396.90   9.08    20.6  
356     21.0  396.90   5.64    23.9  
357     21.0  393.45   6.48    22.0  
358     21.0  396.90   7.88    11.9  

[359 rows x 14 columns]

- INDUS가 5.0 이상이면서 B가 394 이상인 데이터 추출

In [8]:
# result = df_boston[(조건식1) | (조건식2) & (조건식3)]
# 조건식 = df_boston['추출할행'] 연산기호 및 식
result = df_boston[(df_boston['INDUS'] >= 5.0) & (df_boston['B'] >= 394)].reset_index(drop = True)

result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
1    0.08829  12.5   7.87   0.0  0.524  6.012  66.6  5.5605  5.0  311.0   
2    0.14455  12.5   7.87   0.0  0.524  6.172  96.1  5.9505  5.0  311.0   
3    0.11747  12.5   7.87   0.0  0.524  6.009  82.9  6.2267  5.0  311.0   
4    0.62976   0.0   8.14   0.0  0.538  5.949  61.8  4.7075  4.0  307.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
138  0.17783   0.0   9.69   0.0  0.585  5.569  73.5  2.3999  6.0  391.0   
139  0.22438   0.0   9.69   0.0  0.585  6.027  79.7  2.4982  6.0  391.0   
140  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
141  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
142  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       17.8  396.90   9.14    21.6  
1       15.2  395.60  12.43    22.9  
2       15.2  396.90  19.15    27.1  
3       15.2  396.90  13.27    18.9  
4       21.0  396.90   8.26    20.4  
..       ...     ...    ...     ...  
138     19.2  395.77  15.10    17.5  
139     19.2  396.90  14.33    16.8  
140     21.0  396.90   9.08    20.6  
141     21.0  396.90   5.64    23.9  
142     21.0  396.90   7.88    11.9  

[143 rows x 14 columns]

## iloc와 loc의 문법

In [9]:
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

# iloc로만 추출
- 슬라이싱 [이상 : 미만]

In [10]:
df_boston.iloc[:3, :3]

CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07
2  0.02729   0.0   7.07

# loc로만 추출
- 슬라이싱 [이상 : 이하]

In [11]:
df_boston.loc[:2, ["CRIM", "ZN", "INDUS", "target"]]

CRIM    ZN  INDUS  target
0  0.00632  18.0   2.31    24.0
1  0.02731   0.0   7.07    21.6
2  0.02729   0.0   7.07    34.7

In [12]:
result = df_boston.loc[df_boston['INDUS']>=5.0, ["CRIM", "ZN", "INDUS"]].reset_index(drop = True)
result

CRIM    ZN  INDUS
0    0.02731   0.0   7.07
1    0.02729   0.0   7.07
2    0.08829  12.5   7.87
3    0.14455  12.5   7.87
4    0.21124  12.5   7.87
..       ...   ...    ...
381  0.06263   0.0  11.93
382  0.04527   0.0  11.93
383  0.06076   0.0  11.93
384  0.10959   0.0  11.93
385  0.04741   0.0  11.93

[386 rows x 3 columns]

In [13]:
result = df_boston.loc[(df_boston['INDUS'] >= 5.0) & (df_boston['B'] >= 394), ["CRIM", "ZN", "INDUS"]].reset_index(drop=True)

result

CRIM    ZN  INDUS
0    0.02731   0.0   7.07
1    0.08829  12.5   7.87
2    0.14455  12.5   7.87
3    0.11747  12.5   7.87
4    0.62976   0.0   8.14
..       ...   ...    ...
138  0.17783   0.0   9.69
139  0.22438   0.0   9.69
140  0.04527   0.0  11.93
141  0.06076   0.0  11.93
142  0.04741   0.0  11.93

[143 rows x 3 columns]

## 결측치 다루기

In [14]:
import pandas as pd
import numpy as np

np.random.seed(0) # 랜덤으로 숫자를 추출하지만, 첫 결과는 고정시킨다. 실험조건을 동일하게 맞춤
data = np.random.randint(0, 10, size = (10, 3)).astype(float)
data

array([[5., 0., 3.],
       [3., 7., 9.],
       [3., 5., 2.],
       [4., 7., 6.],
       [8., 8., 1.],
       [6., 7., 7.],
       [8., 1., 5.],
       [9., 8., 9.],
       [4., 3., 0.],
       [3., 5., 0.]])

In [15]:
data[data < 3] = np.nan
print(data)

[[ 5. nan  3.]
 [ 3.  7.  9.]
 [ 3.  5. nan]
 [ 4.  7.  6.]
 [ 8.  8. nan]
 [ 6.  7.  7.]
 [ 8. nan  5.]
 [ 9.  8.  9.]
 [ 4.  3. nan]
 [ 3.  5. nan]]


In [16]:
df = pd.DataFrame(data, columns=["col1", "col2", "col3"]) # 외부에서 새로운 데이터 가져옴

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     float64
 1   col2    8 non-null      float64
 2   col3    6 non-null      float64
dtypes: float64(3)
memory usage: 368.0 bytes


In [17]:
df.isna().sum()

col1    0
col2    2
col3    4
dtype: int64

In [18]:
# 평균으로 대치 해보기

In [19]:
avg = df.mean()
avg

col1    5.30
col2    6.25
col3    6.50
dtype: float64

In [20]:
mean_col2 = df["col2"].mean()
mean_col3 = df["col3"].mean()

df["col2"].fillna(mean_col2)
df["col3"].fillna(mean_col3)

df

col1  col2  col3
0   5.0   NaN   3.0
1   3.0   7.0   9.0
2   3.0   5.0   NaN
3   4.0   7.0   6.0
4   8.0   8.0   NaN
5   6.0   7.0   7.0
6   8.0   NaN   5.0
7   9.0   8.0   9.0
8   4.0   3.0   NaN
9   3.0   5.0   NaN

In [21]:
data[data < 4] = np.nan
print(data)

[[ 5. nan nan]
 [nan  7.  9.]
 [nan  5. nan]
 [ 4.  7.  6.]
 [ 8.  8. nan]
 [ 6.  7.  7.]
 [ 8. nan  5.]
 [ 9.  8.  9.]
 [ 4. nan nan]
 [nan  5. nan]]


In [22]:
df.isna().sum()

col1    3
col2    3
col3    5
dtype: int64

In [23]:
mode_col1 = df["col1"].mode()[0]
mode_col2 = df["col2"].mode()[0]
mode_col3 = df["col3"].mode()[0]

df["col1"].fillna(mode_col1, inplace=True)
df["col2"].fillna(mode_col2, inplace=True)
df["col3"].fillna(mode_col3, inplace=True)

df

col1  col2  col3
0   5.0   7.0   9.0
1   4.0   7.0   9.0
2   4.0   5.0   9.0
3   4.0   7.0   6.0
4   8.0   8.0   9.0
5   6.0   7.0   7.0
6   8.0   7.0   5.0
7   9.0   8.0   9.0
8   4.0   7.0   9.0
9   4.0   5.0   9.0

## 행 추가

In [24]:
df = pd.DataFrame({
    "이름": ["Evan", "Sara", "Chris", "Messi", "Woods", "Jordan"], 
    "국어": [70, 90, None, None, 100, 85], 
    "영어": [65, 100, None, 90, 70, 80]
})

df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0

In [25]:
df.loc[6, "이름":"영어"] = ["Kim", 50, 60]
df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0
6     Kim   50.0   60.0

In [27]:
# 국어 점수가 90점 이상이면 "A"
# 국어 점수가 80~89 "B"
# 국어점수가 70~79 "C"
# 나머지는 F
# df['등급'] =   사용하기

1. 데이터가 주어졌고, pandas 데이터 프레임으로 변경되어 df로 지정된 상태로 주어짐
2. 우리가 만드려는 것은 국어 점수에 따른 등급을 만들어보려고함
3. 국어 점수에 따른 등급을 나타내는 조건문을 지정해야한다.
4. 국어점수로 나타낸 등급을 데이터 프레임에 적용시킨다.

In [28]:
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "F"

df['등급'] = df['국어'].apply(grade)
df

이름     국어     영어 등급
0    Evan   70.0   65.0  C
1    Sara   90.0  100.0  A
2   Chris    NaN    NaN  F
3   Messi    NaN   90.0  F
4   Woods  100.0   70.0  A
5  Jordan   85.0   80.0  B
6     Kim   50.0   60.0  F

## 다른 방법

In [29]:
condition_list = [(df["국어"] >= 90), (df['국어'] >= 80) & (df['국어'] < 90), (df['국어'] >= 70) & (df['국어'] < 80)]
choice_list = ["A", "B", "C"]
df['점수'] = np.select(condition_list, choice_list, default = "F")
df

이름     국어     영어 등급 점수
0    Evan   70.0   65.0  C  C
1    Sara   90.0  100.0  A  A
2   Chris    NaN    NaN  F  F
3   Messi    NaN   90.0  F  F
4   Woods  100.0   70.0  A  A
5  Jordan   85.0   80.0  B  B
6     Kim   50.0   60.0  F  F

- numpy.where, 조건식 한번만 적용

if 조건식, 참, 거짓

In [ ]:
# np.where(조건식, 참, np.where(조건식, 참, np.where(조건식, 참)))
# np.select(다중 조건식, 다중 결과값, default >> else 조건)

In [30]:
%%timeit

condition_list = [(df["국어"] >= 90), (df["국어"] >= 80) & (df["국어"] < 90),  (df["국어"] >= 70) & (df["국어"] < 80)]
chocie_list = ["A", "B", "C"]
df['점수'] = np.select(condition_list, chocie_list, default = "F")
df

556 µs ± 16.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# 날짜 데이터 핸들링

In [31]:
date_string = "2023-03-02"
print(type(date_string))

datetime_obj = pd.to_datetime(date_string)
print(datetime_obj)
print(type(datetime_obj))

<class 'str'>
2023-03-02 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>


In [32]:
date_list = ["2023-03-02"]
print(type(date_list))

datetime_obj = pd.to_datetime(date_list)
print(datetime_obj)
print(type(datetime_obj))

<class 'list'>
DatetimeIndex(['2023-03-02'], dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


## 데이터 가져오기
- raw_sales.csv 가져오기

In [33]:
sales = pd.read_csv("./data/raw_sales.csv")
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   datesold      29580 non-null  object
 1   postcode      29580 non-null  int64 
 2   price         29580 non-null  int64 
 3   propertyType  29580 non-null  object
 4   bedrooms      29580 non-null  int64 
dtypes: int64(3), object(2)
memory usage: 1.1+ MB


In [34]:
sales.head()

datesold  postcode   price propertyType  bedrooms
0  2007-02-07 00:00:00      2607  525000        house         4
1  2007-02-27 00:00:00      2906  290000        house         3
2  2007-03-07 00:00:00      2905  328000        house         3
3  2007-03-09 00:00:00      2905  380000        house         4
4  2007-03-21 00:00:00      2906  310000        house         3

In [37]:
sales['datesold'] = pd.to_datetime(sales['datesold'])
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB


In [38]:
sales.head()

datesold  postcode   price propertyType  bedrooms
0 2007-02-07      2607  525000        house         4
1 2007-02-27      2906  290000        house         3
2 2007-03-07      2905  328000        house         3
3 2007-03-09      2905  380000        house         4
4 2007-03-21      2906  310000        house         3

In [39]:
# 연도, 월, 일
sales['year'] = sales['datesold'].dt.year
sales['month'] = sales['datesold'].dt.month
sales['day'] = sales['datesold'].dt.day

sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


## shift 기능

In [40]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df.head(3)

datesold   price
0 2007-02-07  525000
1 2007-02-27  290000
2 2007-03-07  328000

In [41]:
temp_df['shifted_v1'] = temp_df['price'].shift(1, fill_value=0).astype(int)

temp_df.head()

datesold   price  shifted_v1
0 2007-02-07  525000           0
1 2007-02-27  290000      525000
2 2007-03-07  328000      290000
3 2007-03-09  380000      328000
4 2007-03-21  310000      380000

In [42]:
temp_df['shifted_v1'] = temp_df['price'].shift(1, fill_value=0).astype(int)
temp_df['diff'] = temp_df['price'] - temp_df['shifted_v1']
temp_df.head()

datesold   price  shifted_v1    diff
0 2007-02-07  525000           0  525000
1 2007-02-27  290000      525000 -235000
2 2007-03-07  328000      290000   38000
3 2007-03-09  380000      328000   52000
4 2007-03-21  310000      380000  -70000

In [43]:
temp_df['shifted_v2'] = temp_df['price'].shift(2, fill_value=0).astype(int)
temp_df['diff2'] = temp_df['price'] - temp_df['shifted_v2']
temp_df.head()

datesold   price  shifted_v1    diff  shifted_v2   diff2
0 2007-02-07  525000           0  525000           0  525000
1 2007-02-27  290000      525000 -235000           0  290000
2 2007-03-07  328000      290000   38000      525000 -197000
3 2007-03-09  380000      328000   52000      290000   90000
4 2007-03-21  310000      380000  -70000      328000  -18000

In [44]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()

temp_df['shifted_v3'] = temp_df['price'].shift(-1, fill_value=0).astype(int)
temp_df['shifted_v4'] = temp_df['price'].shift(-2, fill_value=0).astype(int)
temp_df.tail()

datesold   price  shifted_v3  shifted_v4
29575 2019-07-25  500000      560000      464950
29576 2019-07-25  560000      464950      589000
29577 2019-07-26  464950      589000      775000
29578 2019-07-26  589000      775000           0
29579 2019-07-26  775000           0           0

In [45]:
temp_df.head()

datesold   price  shifted_v3  shifted_v4
0 2007-02-07  525000      290000      328000
1 2007-02-27  290000      328000      380000
2 2007-03-07  328000      380000      310000
3 2007-03-09  380000      310000      465000
4 2007-03-21  310000      465000      399000

In [46]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


In [47]:
sales['한글날짜'] = sales['datesold'].dt.strftime('%Y년 %m월 %d일')
sales.head()

datesold  postcode   price propertyType  bedrooms  year  month  day  \
0 2007-02-07      2607  525000        house         4  2007      2    7   
1 2007-02-27      2906  290000        house         3  2007      2   27   
2 2007-03-07      2905  328000        house         3  2007      3    7   
3 2007-03-09      2905  380000        house         4  2007      3    9   
4 2007-03-21      2906  310000        house         3  2007      3   21   

            한글날짜  
0  2007년 02월 07일  
1  2007년 02월 27일  
2  2007년 03월 07일  
3  2007년 03월 09일  
4  2007년 03월 21일

In [35]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import statsmodels
import scipy
import seaborn as sns

print(pd.__version__)
print(np.__version__)
print(matplotlib.__version__)
print(statsmodels.__version__)
print(scipy.__version__)
print(sns.__version__)

2.0.3
1.25.2
3.7.2
0.14.0
1.11.1
0.12.2


In [48]:
DATA_PATH = './'
covidtotals = pd.read_csv(DATA_PATH + "data/covidtotalswithmissings.csv")
covidtotals

iso_code    lastdate        location  total_cases  total_deaths  \
0        AFG  2020-06-01     Afghanistan        15205           257   
1        ALB  2020-06-01         Albania         1137            33   
2        DZA  2020-06-01         Algeria         9394           653   
3        AND  2020-06-01         Andorra          764            51   
4        AGO  2020-06-01          Angola           86             4   
..       ...         ...             ...          ...           ...   
205      VNM  2020-06-01         Vietnam          328             0   
206      ESH  2020-06-01  Western Sahara           23             1   
207      YEM  2020-06-01           Yemen          323            80   
208      ZMB  2020-06-01          Zambia         1057             7   
209      ZWE  2020-06-01        Zimbabwe          178             4   

     total_cases_pm  total_deaths_pm  population  pop_density  median_age  \
0           390.589            6.602  38928341.0       54.422        18.6   
1           395.093           11.467   2877800.0      104.871        38.0   
2           214.225           14.891  43851043.0       17.348        29.1   
3          9888.048          660.066     77265.0      163.755         NaN   
4             2.617            0.122  32866268.0       23.890        16.8   
..              ...              ...         ...          ...         ...   
205           3.370            0.000  97338583.0      308.127        32.6   
206          38.505            1.674    597330.0          NaN        28.4   
207          10.829            2.682  29825968.0       53.508        20.3   
208          57.496            0.381  18383956.0       22.995        17.7   
209          11.976            0.269  14862927.0       42.729        19.6   

     gdp_per_capita  hosp_beds  
0          1803.987       0.50  
1         11803.431       2.89  
2         13913.839       1.90  
3               NaN        NaN  
4          5819.495        NaN  
..              ...        ...  
205        6171.884       2.60  
206             NaN        NaN  
207        1479.147       0.70  
208        3689.251       2.00  
209        1899.775       1.70  

[210 rows x 12 columns]

In [49]:
covidtotals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   iso_code         210 non-null    object 
 1   lastdate         210 non-null    object 
 2   location         210 non-null    object 
 3   total_cases      210 non-null    int64  
 4   total_deaths     210 non-null    int64  
 5   total_cases_pm   209 non-null    float64
 6   total_deaths_pm  209 non-null    float64
 7   population       210 non-null    float64
 8   pop_density      198 non-null    float64
 9   median_age       186 non-null    float64
 10  gdp_per_capita   182 non-null    float64
 11  hosp_beds        164 non-null    float64
dtypes: float64(7), int64(2), object(3)
memory usage: 19.8+ KB


In [51]:
pd.set_option('display.width', 80)
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 20)
pd.options.display.float_format = '{:,.2f}'.format

In [52]:
covidtotals = covidtotals.set_index('iso_code')
covidtotals.head()

lastdate     location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                       
AFG       2020-06-01  Afghanistan        15205           257          390.59   
ALB       2020-06-01      Albania         1137            33          395.09   
DZA       2020-06-01      Algeria         9394           653          214.22   
AND       2020-06-01      Andorra          764            51        9,888.05   
AGO       2020-06-01       Angola           86             4            2.62   

          total_deaths_pm    population  pop_density  median_age  \
iso_code                                                           
AFG                  6.60 38,928,341.00        54.42       18.60   
ALB                 11.47  2,877,800.00       104.87       38.00   
DZA                 14.89 43,851,043.00        17.35       29.10   
AND                660.07     77,265.00       163.75         NaN   
AGO                  0.12 32,866,268.00        23.89       16.80   

          gdp_per_capita  hosp_beds  
iso_code                             
AFG             1,803.99       0.50  
ALB            11,803.43       2.89  
DZA            13,913.84       1.90  
AND                  NaN        NaN  
AGO             5,819.49        NaN

### 결측치 처리
- 인구통계 컬럼에서 결측치 데이터를 확인
- 컬럼방향으로 결측치의 갯수를 파악함
- 5가지 인구통계 변수중에서 3개가 누락된 곳, 4개가 누락된 곳 확인

In [54]:
totvars = ['location','total_cases','total_deaths','total_cases_pm','total_deaths_pm']
demovars = ['population','pop_density','median_age','gdp_per_capita', 'hosp_beds']

In [55]:
covidtotals[demovars].isnull().sum(axis=0)

population         0
pop_density       12
median_age        24
gdp_per_capita    28
hosp_beds         46
dtype: int64

In [56]:
covidtotals.iloc[2:4,:]

lastdate location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                   
DZA       2020-06-01  Algeria         9394           653          214.22   
AND       2020-06-01  Andorra          764            51        9,888.05   

          total_deaths_pm    population  pop_density  median_age  \
iso_code                                                           
DZA                 14.89 43,851,043.00        17.35       29.10   
AND                660.07     77,265.00       163.75         NaN   

          gdp_per_capita  hosp_beds  
iso_code                             
DZA            13,913.84       1.90  
AND                  NaN        NaN

In [57]:
demovars_misscnt = covidtotals[demovars].isnull().sum(axis=1)
demovars_misscnt.value_counts()

0    156
1     24
2     12
3     10
4      8
Name: count, dtype: int64

## 미션 1.
- 결측치가 3개 이상인 데이터를 추출하시오.

In [58]:
covidtotals.loc[demovars_misscnt >= 3, ['location'] + demovars].T

iso_code             AND       AIA                              BES  \
location         Andorra  Anguilla  Bonaire Sint Eustatius and Saba   
population     77,265.00 15,002.00                        26,221.00   
pop_density       163.75       NaN                              NaN   
median_age           NaN       NaN                              NaN   
gdp_per_capita       NaN       NaN                              NaN   
hosp_beds            NaN       NaN                              NaN   

iso_code                           VGB             FRO               FLK  \
location        British Virgin Islands  Faeroe Islands  Falkland Islands   
population                   30,237.00       48,865.00          3,483.00   
pop_density                     207.97           35.31               NaN   
median_age                         NaN             NaN               NaN   
gdp_per_capita                     NaN             NaN               NaN   
hosp_beds                          NaN             NaN               NaN   

iso_code              GIB        GRL       GGY          IMN        JEY  \
location        Gibraltar  Greenland  Guernsey  Isle of Man     Jersey   
population      33,691.00  56,772.00 67,052.00    85,032.00 101,073.00   
pop_density      3,457.10       0.14       NaN       147.87        NaN   
median_age            NaN        NaN       NaN          NaN        NaN   
gdp_per_capita        NaN        NaN       NaN          NaN        NaN   
hosp_beds             NaN        NaN       NaN          NaN        NaN   

iso_code                XKX         MSR                       MNP  \
location             Kosovo  Montserrat  Northern Mariana Islands   
population     1,932,774.00    4,999.00                 57,557.00   
pop_density             NaN         NaN                    119.88   
median_age              NaN         NaN                       NaN   
gdp_per_capita          NaN         NaN                       NaN   
hosp_beds               NaN         NaN                       NaN   

iso_code                 TWN                       TCA      VAT  \
location              Taiwan  Turks and Caicos Islands  Vatican   
population     23,816,775.00                 38,718.00   809.00   
pop_density              NaN                     37.31      NaN   
median_age             42.20                       NaN      NaN   
gdp_per_capita           NaN                       NaN      NaN   
hosp_beds                NaN                       NaN      NaN   

iso_code                   ESH  
location        Western Sahara  
population          597,330.00  
pop_density                NaN  
median_age               28.40  
gdp_per_capita             NaN  
hosp_beds                  NaN

In [59]:
filtered_data = covidtotals[demovars_misscnt >= 3]
filtered_data

lastdate                         location  total_cases  \
iso_code                                                             
AND       2020-06-01                          Andorra          764   
AIA       2020-06-01                         Anguilla            3   
BES       2020-06-01  Bonaire Sint Eustatius and Saba            7   
VGB       2020-06-01           British Virgin Islands            8   
FRO       2020-06-01                   Faeroe Islands          187   
FLK       2020-06-01                 Falkland Islands           13   
GIB       2020-06-01                        Gibraltar          169   
GRL       2020-06-01                        Greenland           13   
GGY       2020-06-01                         Guernsey          252   
IMN       2020-06-01                      Isle of Man          336   
JEY       2020-06-01                           Jersey          308   
XKX       2020-06-01                           Kosovo         1064   
MSR       2020-06-01                       Montserrat           11   
MNP       2020-06-01         Northern Mariana Islands           22   
TWN       2020-06-01                           Taiwan          442   
TCA       2020-06-01         Turks and Caicos Islands           12   
VAT       2020-06-01                          Vatican           12   
ESH       2020-06-01                   Western Sahara           23   

          total_deaths  total_cases_pm  total_deaths_pm    population  \
iso_code                                                                
AND                 51        9,888.05           660.07     77,265.00   
AIA                  0          199.97             0.00     15,002.00   
BES                  0          266.96             0.00     26,221.00   
VGB                  1          264.58            33.07     30,237.00   
FRO                  0        3,826.87             0.00     48,865.00   
FLK                  0        3,732.41             0.00      3,483.00   
GIB                  0        5,016.18             0.00     33,691.00   
GRL                  0          228.99             0.00     56,772.00   
GGY                 13        3,758.28           193.88     67,052.00   
IMN                 24        3,951.45           282.25     85,032.00   
JEY                 29        3,047.30           286.92    101,073.00   
XKX                 30          550.50            15.52  1,932,774.00   
MSR                  1        2,200.44           200.04      4,999.00   
MNP                  2          382.23            34.75     57,557.00   
TWN                  7           18.56             0.29 23,816,775.00   
TCA                  1          309.93            25.83     38,718.00   
VAT                  0       14,833.13             0.00        809.00   
ESH                  1           38.51             1.67    597,330.00   

          pop_density  median_age  gdp_per_capita  hosp_beds  
iso_code                                                      
AND            163.75         NaN             NaN        NaN  
AIA               NaN         NaN             NaN        NaN  
BES               NaN         NaN             NaN        NaN  
VGB            207.97         NaN             NaN        NaN  
FRO             35.31         NaN             NaN        NaN  
FLK               NaN         NaN             NaN        NaN  
GIB          3,457.10         NaN             NaN        NaN  
GRL              0.14         NaN             NaN        NaN  
GGY               NaN         NaN             NaN        NaN  
IMN            147.87         NaN             NaN        NaN  
JEY               NaN         NaN             NaN        NaN  
XKX               NaN         NaN             NaN        NaN  
MSR               NaN         NaN             NaN        NaN  
MNP            119.88         NaN             NaN        NaN  
TWN               NaN       42.20             NaN        NaN  
TCA             37.31         NaN             NaN        NaN  
VAT             

In [60]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])

# print(s1, "\n", s2)
print(s1+s2)

a    2
b    4
c    6
d    8
dtype: int64


## 코로나 관련 변수만 추출
- 결측값이 있는지 확인
- 결측값이 있는 국가가 하나 존재함
- totvars 사용

In [69]:
covidtotals[totvars].isnull().sum(axis=0)

location           0
total_cases        0
total_deaths       0
total_cases_pm     1
total_deaths_pm    1
dtype: int64

In [62]:
demovars_misscnt = covidtotals[totvars].isnull().sum(axis=1)
demovars_misscnt.value_counts()

0    209
2      1
Name: count, dtype: int64

In [63]:
covidtotals.loc[demovars_misscnt>0].T

iso_code                 HKG
lastdate          2020-05-26
location           Hong Kong
total_cases                0
total_deaths               0
total_cases_pm           NaN
total_deaths_pm          NaN
population      7,496,988.00
pop_density         7,039.71
median_age             44.80
gdp_per_capita     56,054.92
hosp_beds                NaN

In [64]:
covidtotalsonly = covidtotals.loc[:, totvars]
covidtotalsonly['total_cases_q'] = pd.qcut(covidtotalsonly['total_cases'],
                                          labels = ['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                          q=5, precision=0)
covidtotalsonly['total_deaths_q'] = pd.qcut(covidtotalsonly['total_deaths'],
                                          labels = ['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                          q=5, precision=0)
covidtotalsonly.head()

location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                           
AFG       Afghanistan        15205           257          390.59   
ALB           Albania         1137            33          395.09   
DZA           Algeria         9394           653          214.22   
AND           Andorra          764            51        9,888.05   
AGO            Angola           86             4            2.62   

          total_deaths_pm total_cases_q total_deaths_q  
iso_code                                                
AFG                  6.60            높음             높음  
ALB                 11.47            중간             중간  
DZA                 14.89            높음           매우높음  
AND                660.07            중간             중간  
AGO                  0.12          매우낮음             낮음

In [65]:
pd.crosstab(covidtotalsonly['total_cases_q'], covidtotalsonly['total_deaths_q'])

total_deaths_q  매우낮음  낮음  중간  높음  매우높음
total_cases_q                         
매우낮음              34   7   1   0     0
낮음                12  19  10   1     0
중간                 1  13  15  13     0
높음                 0   0  12  24     6
매우높음               0   0   2   4    36

In [66]:
covidtotals.loc[:, totvars]

location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                              
AFG          Afghanistan        15205           257          390.59   
ALB              Albania         1137            33          395.09   
DZA              Algeria         9394           653          214.22   
AND              Andorra          764            51        9,888.05   
AGO               Angola           86             4            2.62   
...                  ...          ...           ...             ...   
VNM              Vietnam          328             0            3.37   
ESH       Western Sahara           23             1           38.51   
YEM                Yemen          323            80           10.83   
ZMB               Zambia         1057             7           57.50   
ZWE             Zimbabwe          178             4           11.98   

          total_deaths_pm  
iso_code                   
AFG                  6.60  
ALB                 11.47  
DZA                 14.89  
AND                660.07  
AGO                  0.12  
...                   ...  
VNM                  0.00  
ESH                  1.67  
YEM                  2.68  
ZMB                  0.38  
ZWE                  0.27  

[210 rows x 5 columns]

In [67]:
covidtotalsonly[(covidtotalsonly['total_cases_q'] == '낮음') & (covidtotalsonly['total_deaths_q'] == '높음')]

location  total_cases  total_deaths  total_cases_pm  total_deaths_pm  \
iso_code                                                                        
YEM         Yemen          323            80           10.83             2.68   

         total_cases_q total_deaths_q  
iso_code                               
YEM                 낮음             높음

In [68]:
covidtotals.loc[(covidtotalsonly.total_cases_q=="낮음") & (covidtotalsonly.total_deaths_q=="높음")]

lastdate location  total_cases  total_deaths  total_cases_pm  \
iso_code                                                                   
YEM       2020-06-01    Yemen          323            80           10.83   

          total_deaths_pm    population  pop_density  median_age  \
iso_code                                                           
YEM                  2.68 29,825,968.00        53.51       20.30   

          gdp_per_capita  hosp_beds  
iso_code                             
YEM             1,479.15       0.70